language: python
python: 3.7.7
install: pip install -r requirements.txt
script: python manage.py test

deploy:
  provider: heroku
  api_key: 32bc4afc-69fc-4722-a1c8-936d5d732f71
  app: django_sample_web_app
  run: python manage.py migrate
  on: master